/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.chriniko.pollfish.thrift.server.protocol;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-11-22")
public enum LoggingEventPriority implements org.apache.thrift.TEnum {
  NORMAL(0),
  MEDIUM(1),
  CRITICAL(2);

  private final int value;

  private LoggingEventPriority(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static LoggingEventPriority findByValue(int value) { 
    switch (value) {
      case 0:
        return NORMAL;
      case 1:
        return MEDIUM;
      case 2:
        return CRITICAL;
      default:
        return null;
    }
  }
}
