/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.chriniko.pollfish.thrift.server.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-11-22")
public class UserInfoEventType extends org.apache.thrift.TUnion<UserInfoEventType, UserInfoEventType._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserInfoEventType");
  private static final org.apache.thrift.protocol.TField LOGGED_IN_FIELD_DESC = new org.apache.thrift.protocol.TField("loggedIn", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField LOGGED_OUT_FIELD_DESC = new org.apache.thrift.protocol.TField("loggedOut", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField CLICKED_ON_ADVERTISEMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("clickedOnAdvertisement", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOGGED_IN((short)1, "loggedIn"),
    LOGGED_OUT((short)2, "loggedOut"),
    CLICKED_ON_ADVERTISEMENT((short)3, "clickedOnAdvertisement");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOGGED_IN
          return LOGGED_IN;
        case 2: // LOGGED_OUT
          return LOGGED_OUT;
        case 3: // CLICKED_ON_ADVERTISEMENT
          return CLICKED_ON_ADVERTISEMENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOGGED_IN, new org.apache.thrift.meta_data.FieldMetaData("loggedIn", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "LoggedIn")));
    tmpMap.put(_Fields.LOGGED_OUT, new org.apache.thrift.meta_data.FieldMetaData("loggedOut", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "LoggedOut")));
    tmpMap.put(_Fields.CLICKED_ON_ADVERTISEMENT, new org.apache.thrift.meta_data.FieldMetaData("clickedOnAdvertisement", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "ClickedOnAdvertisement")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserInfoEventType.class, metaDataMap);
  }

  public UserInfoEventType() {
    super();
  }

  public UserInfoEventType(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public UserInfoEventType(UserInfoEventType other) {
    super(other);
  }
  public UserInfoEventType deepCopy() {
    return new UserInfoEventType(this);
  }

  public static UserInfoEventType loggedIn(LoggedIn value) {
    UserInfoEventType x = new UserInfoEventType();
    x.setLoggedIn(value);
    return x;
  }

  public static UserInfoEventType loggedOut(LoggedOut value) {
    UserInfoEventType x = new UserInfoEventType();
    x.setLoggedOut(value);
    return x;
  }

  public static UserInfoEventType clickedOnAdvertisement(ClickedOnAdvertisement value) {
    UserInfoEventType x = new UserInfoEventType();
    x.setClickedOnAdvertisement(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case LOGGED_IN:
        if (value instanceof LoggedIn) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type LoggedIn for field 'loggedIn', but got " + value.getClass().getSimpleName());
      case LOGGED_OUT:
        if (value instanceof LoggedOut) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type LoggedOut for field 'loggedOut', but got " + value.getClass().getSimpleName());
      case CLICKED_ON_ADVERTISEMENT:
        if (value instanceof ClickedOnAdvertisement) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type ClickedOnAdvertisement for field 'clickedOnAdvertisement', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case LOGGED_IN:
          if (field.type == LOGGED_IN_FIELD_DESC.type) {
            LoggedIn loggedIn;
            loggedIn = new LoggedIn();
            loggedIn.read(iprot);
            return loggedIn;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LOGGED_OUT:
          if (field.type == LOGGED_OUT_FIELD_DESC.type) {
            LoggedOut loggedOut;
            loggedOut = new LoggedOut();
            loggedOut.read(iprot);
            return loggedOut;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case CLICKED_ON_ADVERTISEMENT:
          if (field.type == CLICKED_ON_ADVERTISEMENT_FIELD_DESC.type) {
            ClickedOnAdvertisement clickedOnAdvertisement;
            clickedOnAdvertisement = new ClickedOnAdvertisement();
            clickedOnAdvertisement.read(iprot);
            return clickedOnAdvertisement;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LOGGED_IN:
        LoggedIn loggedIn = (LoggedIn)value_;
        loggedIn.write(oprot);
        return;
      case LOGGED_OUT:
        LoggedOut loggedOut = (LoggedOut)value_;
        loggedOut.write(oprot);
        return;
      case CLICKED_ON_ADVERTISEMENT:
        ClickedOnAdvertisement clickedOnAdvertisement = (ClickedOnAdvertisement)value_;
        clickedOnAdvertisement.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case LOGGED_IN:
          LoggedIn loggedIn;
          loggedIn = new LoggedIn();
          loggedIn.read(iprot);
          return loggedIn;
        case LOGGED_OUT:
          LoggedOut loggedOut;
          loggedOut = new LoggedOut();
          loggedOut.read(iprot);
          return loggedOut;
        case CLICKED_ON_ADVERTISEMENT:
          ClickedOnAdvertisement clickedOnAdvertisement;
          clickedOnAdvertisement = new ClickedOnAdvertisement();
          clickedOnAdvertisement.read(iprot);
          return clickedOnAdvertisement;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LOGGED_IN:
        LoggedIn loggedIn = (LoggedIn)value_;
        loggedIn.write(oprot);
        return;
      case LOGGED_OUT:
        LoggedOut loggedOut = (LoggedOut)value_;
        loggedOut.write(oprot);
        return;
      case CLICKED_ON_ADVERTISEMENT:
        ClickedOnAdvertisement clickedOnAdvertisement = (ClickedOnAdvertisement)value_;
        clickedOnAdvertisement.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case LOGGED_IN:
        return LOGGED_IN_FIELD_DESC;
      case LOGGED_OUT:
        return LOGGED_OUT_FIELD_DESC;
      case CLICKED_ON_ADVERTISEMENT:
        return CLICKED_ON_ADVERTISEMENT_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public LoggedIn getLoggedIn() {
    if (getSetField() == _Fields.LOGGED_IN) {
      return (LoggedIn)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'loggedIn' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLoggedIn(LoggedIn value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.LOGGED_IN;
    value_ = value;
  }

  public LoggedOut getLoggedOut() {
    if (getSetField() == _Fields.LOGGED_OUT) {
      return (LoggedOut)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'loggedOut' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLoggedOut(LoggedOut value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.LOGGED_OUT;
    value_ = value;
  }

  public ClickedOnAdvertisement getClickedOnAdvertisement() {
    if (getSetField() == _Fields.CLICKED_ON_ADVERTISEMENT) {
      return (ClickedOnAdvertisement)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'clickedOnAdvertisement' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setClickedOnAdvertisement(ClickedOnAdvertisement value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.CLICKED_ON_ADVERTISEMENT;
    value_ = value;
  }

  public boolean isSetLoggedIn() {
    return setField_ == _Fields.LOGGED_IN;
  }


  public boolean isSetLoggedOut() {
    return setField_ == _Fields.LOGGED_OUT;
  }


  public boolean isSetClickedOnAdvertisement() {
    return setField_ == _Fields.CLICKED_ON_ADVERTISEMENT;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof UserInfoEventType) {
      return equals((UserInfoEventType)other);
    } else {
      return false;
    }
  }

  public boolean equals(UserInfoEventType other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(UserInfoEventType other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
